train_set: ./data/data_v2/anns/rpcocos/train.json
evaluate_set: ./data/data_v2/anns/rpcocos/testA.json
seg_gt_path: ./data/data_v2/masks/rpcocos
log_path: ./log/refcoco_refcoco
evaluate_model: ./log/refcoco_selective_twice_refcoco/models/best_map.h5
evaluate_name: selective_ST_val
save_path: /data2/dxw/refcoco_pole_testA

batch_size: 24
workers: 32

num_query: 18


steps: 10
